docs(blog): speeding up your Program Indicators with Tracker-to-Aggre…
dhis2/developer-portal pull request #76
Opened 2022-04-29 12:51 UTC by claudemamo

…gate

2022-05-09 08:33 UTC, germanviscuso reviewed
Approved

2022-05-10 06:40 UTC, amcgee requested changes
Will review the content later today, but added a minor point that jumped out at me and could be fixed quickly

2022-05-10 06:40 UTC, amcgee commented on blog/2022-02-10-automating-dhis2-integration-tests-in-junit-5.md
> -author: claudemamo
You should instead add yourself as an author [here](https://github.com/dhis2/developer-portal/blob/fc9a5cea7a5809c3027ae0fa850581f64155a1cf/blog/authors.yml) and include the key to that collection as the `author` field

2022-05-10 06:40 UTC, amcgee commented on blog/2022-04-29-speeding-up-your-program-indicators-with-tracker-to-aggregate.md
> +author: Claude Mamo
Ref above

2022-05-16 07:38 UTC, closed without merging